ui: show tx & script version on tx details
decred/dcrdata pull request #1863
Opened 2021-09-16 16:10 UTC by thi4go

This diff adds the tx and script versions to the tx details areabox.

Before:

![image](https://user-images.githubusercontent.com/2729122/133646966-442ea6b1-f6ef-4f8e-ba38-b3591418a568.png)

After: 

![image](https://user-images.githubusercontent.com/2729122/133647063-ec8b1a14-6dde-4af5-8bed-eabcd722b83a.png)

Let me know if any UI changes are needed for a better UX 👍 

closes #1851

2021-09-16 16:15 UTC, davecgh commented
Every output script has an independent version.  From the screenshot, it appears this is assuming there is only one version for the entire transaction, which isn't the case.

2021-09-16 16:21 UTC, davecgh commented
I just hacked up the HTML of the first transaction I came across on the explorer, but I think this would work:

![image](https://user-images.githubusercontent.com/2115102/133648942-61cda93c-2a21-4e0d-ae21-389c255f4c3e.png)

2021-09-16 16:22 UTC, thi4go commented
Hm understood @davecgh was mistakenly assuming all output scripts from a tx had to be the same version. Sweet, will add it to the outputs table 👍

2021-09-16 16:25 UTC, davecgh commented
To be clear, the tx version field looks good and is correct.  It's just the script version that is unique per output.

2021-09-16 16:28 UTC, chappjc commented
> I just hacked up the HTML of the first transaction I came across on the explorer, but I think this would work:
> 
> ![image](https://user-images.githubusercontent.com/2115102/133648942-61cda93c-2a21-4e0d-ae21-389c255f4c3e.png)

That looks good to me too.  We'll just have to play with the responsive design a bit to see if anything gets wonky (e.g. resizing narrow)

2021-09-17 13:38 UTC, thi4go commented
@davecgh @chappjc hey mates, fixed the diff with the suggestions 👍

2021-09-17 16:25 UTC, davecgh approved these changes
Looks proper to me.

2021-09-17 17:10 UTC, chappjc requested changes

2021-09-17 17:10 UTC, chappjc commented on explorer/types/explorertypes.go
> +	TxVersion        int32
This works.  I'm cooking up a PR to do some mempool and DB work, and in that I'm moving `TxVersion` to `TxBasic` and renaming it to just `Version`.  Just a heads up.  This is good like this for now.

2021-09-17 20:48 UTC, chappjc approved these changes
This works, and I have the minor requested changes in a subsequent diff that adjust the mempool structures.

2021-09-17 20:49 UTC, merged